name: Ansible

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs: 
 deploy:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3

     - name: Show files
       run: ls -lR
