name: Ansible

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs: 
 deploy:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3

     - name: Check Ansible Version
       run: ansible --version

     - name: Generate Key
       run: | 
         echo "{{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key
         chmod 400 ansible_key

     - name: Test ssh
       run: 
